### ISSUE TITLE
unexpected result in takeWhile 

### ISSUE THREAD

**Issue by Asmhan** [iabdelkareem/LINQ-To-JavaScript#1]
Documentation:
in Method list  >> takeWhile 
    var ar = [1,2,3,4,5,6,7,8,9];
    ar = ar.takeWhile(o=> o < 4); //Result [5,6,7,8,9]

but the result should be 
// Result [1,2,3]

**Comment by iabdelkareem** [comment]
Dear Asmhan,

Thanks a lot for your interest in my library. I've checked the issue you posted seems there's something wrong with your code i've tested it multiple times as there's a test library including the same case. Maybe you was conflicted and using skipWhile instead of takeWhile. :) But i really appreciate your contribution and hope you can find me more bugs to solve :) Thanks a lot
